// telas/StyleAccessible.tsx
import { StyleSheet } from 'react-native';

export const accessibleStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fafafa', // fundo mais neutro
    padding: 20,
  },
  logo: {
    width: 160,
    height: 160,
    resizeMode: 'contain',
    marginBottom: 50,
  },
  inputContainer: {
    width: '100%',
    marginBottom: 25,
  },
  inputContainerChat: {
    width: '100%',
    marginBottom: 60,
  },
  label: {
    fontSize: 18,
    color: '#111', // contraste mais forte
    marginBottom: 8,
    textAlign: 'left',
  },
  input: {
    width: '100%',
    height: 55,
    backgroundColor: 'white',
    borderRadius: 12,
    paddingHorizontal: 18,
    fontSize: 18,
    color: '#111',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  inputChat: {
    width: '100%',
    height: 55,
    backgroundColor: 'white',
    borderRadius: 12,
    paddingHorizontal: 18,
    fontSize: 18,
    color: '#111',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  inputFocus: {
    borderColor: '#ff7f50', // destaque no foco
    borderWidth: 2,
  },
  btnEsqueciSenha: {
    alignSelf: 'flex-end',
    marginBottom: 25,
  },
  esqueciSenhaTxt: {
    color: '#ff7f50',
    fontSize: 16,
    fontWeight: '600',
  },
  btnEntrar: {
    width: '100%',
    height: 55,
    backgroundColor: '#ff7f50',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  btnTxtEntrar: {
    color: 'white',
    fontSize: 20,
    fontWeight: '700',
  },
  btnCad: {
    width: '100%',
    height: 55,
    backgroundColor: '#003366',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  btnTxtCad: {
    color: 'white',
    fontSize: 20,
    fontWeight: '600',
  },
  btn: {
    width: '100%',
    height: 55,
    backgroundColor: '#004d40',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  btnChat: {
    width: '100%',
    height: 55,
    backgroundColor: '#006151',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  backButton:{
    width: '100%',
    height: 50,
    backgroundColor: '#c44d4d',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  btnTxt: {
    color: 'white',
    fontSize: 20,
    fontWeight: '600',
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  searchBar: {
    width: '100%',
    height: 55,
    backgroundColor: 'white',
    borderRadius: 12,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    fontSize: 18,
    color: '#111',
  },
  searchIcon: {
    marginLeft: 12,
  },
  mainContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  mainText: {
    fontSize: 20,
    color: '#222',
    textAlign: 'center',
    marginBottom: 20,
  },
  bottomNav: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
    height: 65,
    backgroundColor: 'white',
    borderRadius: 32,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
  },
  navItem: {
    alignItems: 'center',
  },
  navIcon: {
    width: 28,
    height: 28,
  },
  activeIndicator: {
    marginTop: 6,
    width: 34,
    height: 4,
    backgroundColor: '#ff7f50', // cor de destaque visível
    borderRadius: 2,
  },
});